---
# Play to deploy
- name: deployment of the fake-backend / battleboat app with gitlab
  hosts: build deploy
#  gather_facts: yes
  become: true
  vars_files:
    - "vars/secret.yml"
    - "vars/main.yml"

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - block:
      - name: update all packages 
        package: name='*' update_only=yes update_cache=yes state=present
        
      - name: Install epel release
        package:  name=epel-release state=present

      - name: install git
        package: name=git state=present
      tags:
        - always

  roles:
    - { role: geerlingguy.pip, tags: [ always ] }
    - { role: geerlingguy.docker, tags: [ always ] }
    - role: 'roles/backend'
    - role: 'roles/frondend'
  
